# Display our Robot
print("Please enter Beep\'s eye symbol:")
eye = input()
print("##########")
print(f"#  {eye}  {eye}  #")
print("#   --   #")
print("##########")
print("    ^^    ")
print("    ^^    ")
print("----^^----")
print("    ^^    ")
print("    ^^    ")
print("    ^^    ")
print("    /\    ")
print("   /  \   ")
print("  /    \  ")